--- 
abstract: Base class for hook mechanism
author: Naoki Okamura (Nyarla) <thotep@nayrla.net>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Class-Hookable
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Scalar::Util: 0
tests: t/*.t
version: 0.01
